item1 = input("what is favourite food from the menu? \n")
item2 = input("What is you 2nd favourite food?\n")
item3 = input("and your 3rd is?\n")
print("Order confirmed! You have ordered:")
print(item1)
print(item2)
print(item3)